// https://www.kroger.com/
export enum Departments {
  FRESH_VEGETABLES_AND_FRUITS = "FRESH_VEGETABLES_AND_FRUITS",
  MEAT_FISH_AND_ALTERNATIVES = "MEAT_FISH_AND_ALTERNATIVES",
  CANNED_FOOD = "CANNED_FOOD",
  BAKING_COOKING = "BAKING_COOKING",
  PASTA_SAUCE = "PASTA_SAUCE",
  GRAINS_BEANS_RICE = "GRAINS_BEANS_RICE",
  DAIRY_AND_EGGS = "DAIRY_AND_EGGS",
  BEER_WINE_LIQUOR = "BEER_WINE_LIQUOR",
  BEVERAGES = "BEVERAGES",
  BAKERY = "BAKERY",
  FROZEN = "FROZEN",
  SNACKS = "SNACKS",
  CLEANING_HOUSEHOLD = "CLEANING_HOUSEHOLD",
  PERSONAL_CARE = "PERSONAL_CARE",
  OTHER = "OTHER",
}
