export enum Departments {
  VEGETABLES_FRUITS = "Groenten & Fruit",
  CHEESE = "Kaas",
  HERBS = "Kruiden",
  SUGAR = "Suiker",
  OILS = "Olie",
  FISH = "Vis",
  EGGS = "Eieren",
  PRESERVED = "Conserven",
  WINE = "Wijn",
  PASTA_RICE_GRAINS = "Pasta, rijst & granen",
  BREAD = "Brood",
  FREEZER = "Diepvriesproducten",
  MILK = "Melkproducten",
  BISCUITS = "Koeken",
}
