export enum Metrics {
  PIECES = "stuk(s)",
  BALLS = "bolletje(s)",
  BRANCHES = "takje(s)",
  AMOUNT = "aantal",
  AMOUNT_ABOUT = "aantal (±)",
  GRAM = "g",
  CENTIMETER = "cm",
  KILO_GRAM = "kg",
  TABLESPOON = "eetlepel",
  TEASPOON = "theelepel",
  LEAVES = "blaadje(s)",
  MILLILITER = "ml",
  DECILITER = "dl",
  CLOVES = "teentje(s)",
}
